site_name: Koor Technologies, Inc. Handbook
site_url: 'https://handbook.koor.tech'
repo_url: https://github.com/koor-tech/handbook
edit_uri: edit/main/docs/
site_author: Koor Technologies, Inc. Team
site_description: "Koor Technologies, Inc. Company Handbook inspired by GitLab's open handbook."
use_directory_urls: true
#copyright: ''
theme:
  name: material
  font: false
  favicon: images/favicon.png
  logo: images/logo.png
  palette:
    - scheme: 'default'
      primary: 'greenish'
      accent: 'deep orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: 'slate'
      primary: 'greenish'
      accent: 'red'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - privacy
    - search.highlight
    - search.share
    - search.suggest
    - tabs
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      #js_files: []
  - redirects:
      redirect_maps: {}
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - nl2br
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
