site_name: Koor Technologies, Inc. Handbook
site_url: "https://handbook.koor.tech"
repo_url: https://github.com/koor-tech/handbook.koor.tech
edit_uri: edit/main/docs/
site_author: Koor Technologies, Inc. Team
site_description: "Koor Technologies, Inc. Company Handbook inspired by GitLab's open handbook."
use_directory_urls: true
copyright: |
  Copyright &copy; 2023 Rook & Koor Storage Distribution Authors All Rights Reserved.
  <br>
  Rook is a trademark of The Linux Foundation®.
  <br>
  Ceph is a trademark or registered trademark of Red Hat, Inc. or its subsidiaries in the United States and other countries.
  <br>
  All trademarks are property of their respective owners in the US and other countries.
theme:
  name: material
  font: false
  favicon: https://koor.tech/images/favicon.svg
  logo: https://koor.tech/images/logo.svg
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "koor-dark"
      accent: "deep orange"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "koor"
      accent: "deep orange"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.tabs.link
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - privacy
    - search.highlight
    - search.share
    - search.suggest
    - tabs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      #js_files: []
  - redirects:
      redirect_maps: {}
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - nl2br
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/koor_tech
    - icon: fontawesome/brands/medium
      link: https://koor.tech/blog/
