[build]
  publish = "site"
  command = "mkdocs build --clean -d site"

[context.development]
  command = "make deploy-development"

[context.production]
  command = "make deploy-production"

# Make sure we are using an uptodate Python version
[build.environment]
  PYTHON_VERSION = "3.7"
