name: "Markdown Lint"

on:
  push:
    paths-ignore:
    - .*
    - CONTRIBUTING.md
    - Makefile
  pull_request:
    paths-ignore:
    - .*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - Makefile

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run markdownlint
      uses: docker://avtodev/markdown-lint:v1.5.0
      with:
        config: '.github/workflows/markdownlint.json'
        args: '*.md ./docs/'
